apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
type: Opaque
stringData:
  .env: |
    DB_HOST=10.22.1.3
    DB_NAME=serverhostingdb
    DB_DIALECT=postgres
    PORT=8080
    FRONTEND_URL=http://localhost:3000/
    RAMGB_PRICE=400
    SSDGB_PRICE=20
    BACKUPGB_PRICE=10
    STRIPE_SECRET_TEST=sk_test_51IHeJCAgE84zSyWHOEAl7lOFsNeu8eBmX4Nl0zNhbTcouPZMVGaQOBBKMQpmJ4fXrasxPkLSdSmHfBn9zJbfXYU000DIwRaJ2v
    DB_USER=timgolding
    DB_PASSWORD=Wetbag55
    JWT_SECRET=5CEBCC5E89EADEE5BF9F3404C800418A34C00D47EB4096E39D8E43E256077834
    INFO_EMAIL_ADDRESS=tgolding55dev@gmail.com
    INFO_EMAIL_PASSWORD=BigDevPassword123!
    TEMPCLUSTERIP=34.105.191.166
    TEMPK8SAPI=http://34.105.191.166:31602/api/v1/